spring.application.name=marketplace

spring.datasource.url=jdbc:mysql://localhost:3306/ebizznessdb
spring.datasource.username=root
spring.datasource.password=DanishDzul2712

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
app.frontend.url=https://v7dj1qmx-5173.asse.devtunnels.ms
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# QR Generation
qr.upload.dir=uploads/qrcodes
app.encryption.key=eBizz@SecureKey
