spring.application.name=ems-backend

#database(mysql) setup
spring.datasource.url=jdbc:mysql://localhost:3306/ebizznessdb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#hibernate properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
